delete load balancer step validation fixed

diff --git a/.github/workflows/destroy.yml b/.github/workflows/destroy.yml
--- a/.github/workflows/destroy.yml
+++ b/.github/workflows/destroy.yml
@@ -65,9 +65,15 @@ jobs:
       
       - name: Delete aws load balancer
         run: |
-          aws elbv2 delete-load-balancer \
-            --load-balancer-arn $(aws elbv2 describe-load-balancers \
-            --query "LoadBalancers[?contains(LoadBalancerName, 'shareduniralb')].LoadBalancerArn" --output text)
+          if ! aws elbv2 describe-load-balancers \
+            --query "LoadBalancers[?contains(LoadBalancerName, 'shareduniralb')].LoadBalancerName" \
+            --output text; then
+            echo "Load balancer 'shareduniralb' not found, skipping deletion."
+          else
+            aws elbv2 delete-load-balancer \
+              --load-balancer-arn $(aws elbv2 describe-load-balancers \
+              --query "LoadBalancers[?contains(LoadBalancerName, 'shareduniralb')].LoadBalancerArn" --output text)
+          fi
 
       - name: Terraform Destroy
         run: terraform destroy -auto-approve
